- hosts: 127.0.0.1
  vars:
    nvim_cfg_url: "https://raw.githubusercontent.com/nicomiguelino/dotfiles/main/init.vim"
    nvim_cfg_dir: "{{ lookup('env', 'HOME') }}/.config/nvim"
    vim_plug_url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    vim_plug_default_dir: "{{ lookup('env', 'HOME') }}/.local/share"
  tasks:
    - name: Install development dependencies
      become: yes
      ansible.builtin.apt:
        update_cache: yes
        name:
          - fzf
          - git
          - neovim
          - ripgrep
          - tmux
          - tree
          - zsh
        state: present
      register: aptout
    - name: Configure Neovim
      ansible.builtin.shell: |
        curl -sfLo {{ nvim_cfg_dir }}/init.vim --create-dirs {{ nvim_cfg_url }}
        curl -sfLo {{ vim_plug_default_dir }}/nvim/site/autoload/plug.vim --create-dirs {{ vim_plug_url }}
        nvim --headless +PlugInstall +qall
      args:
        executable: /bin/bash
