- hosts: 127.0.0.1
  vars:
    nvim_cfg_url: "https://raw.githubusercontent.com/nicomiguelino/dotfiles/main/init.vim"
    nvim_cfg_dir: "{{ lookup('env', 'HOME') }}/.config/nvim"
  become: yes
  tasks:
    - name: Install development dependencies
      ansible.builtin.apt:
        update_cache: yes
        name:
          - neovim
          - tmux
          - ripgrep
          - zsh
          - tree
        state: present
    - name: Configure Neovim
      ansible.builtin.shell: |
        mkdir -p {{nvim_cfg_dir}} && cd $_
        curl -sL {{nvim_cfg_url}} > init.vim

        sh -c 'curl -sfLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
          https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
        nvim --headless +PlugInstall +qall
