- hosts: all
  become: yes
  tasks:
    - name: Install development dependencies
      ansible.builtin.apt:
        update_cache: yes
        name:
          - neovim
          - tmux
          - ripgrep
          - zsh
          - tree
        state: present
